config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  
  resources :restaurants do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end

  get 'pages/about'

  get 'pages/contact'

  root 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  validates :name, :address, :phone, :image, presence: true
  validates :phone, format: { with: /\A\(\d{3}\) \d{3}-\d{4}\z/, message: "must be in the format (123) 456-7890" }
  validates :website, format: { with: /\Ahttps?:\/\/.*\z/, message: "must start with http:// or https://" }


  has_many :reviews

=begin
  searchable do
    text :name, :address
    string  :sort_title do
      title.downcase.gsub(/^(an?|the)/, '')
    end
  end
=end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :check_user, except: [:index, :show, :search]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  def search
    if params[:search].present?
      @restaurants = Restaurant.where( "name like '%#{params[:search]}%' OR address like '%#{params[:search]}%'")
    else
      @restaurants = Restaurant.all
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @reviews = Review.where(restaurant_id: @restaurant.id).order("created_at DESC")
    if !@reviews.blank?
      @avg_rating = Review.average(:rating).round(2)
    end
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def check_user
      unless (user_signed_in? && current_user.admin?)
        redirect_to root_url, alert: "Sorry, only admins can do that!"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone, :website, :image)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">


<%= form_for @restaurant, :html => { :class => "form-horizontal restaurant", multipart: true } do |f| %>

    <% if @restaurant.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="form-controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@restaurant[:name]) %>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="form-controls">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%= error_span(@restaurant[:address]) %>
  </div>
  <div class="form-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="form-controls">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%= error_span(@restaurant[:phone]) %>
  </div>

  <div class="form-group">
    <%= f.label :website, :class => 'control-label' %>
    <div class="form-controls">
      <%= f.text_field :website, :class => 'form-control' %>
    </div>
    <%= error_span(@restaurant[:website]) %>
  </div>

    <div class="form-group">
      <%= f.label :image, :class => 'control-label' %>
      <div class="form-controls">
        <%= f.file_field :image, :class => 'form-control' %>
      </div>
      <%= error_span(@restaurant[:image]) %>
    </div>


    <div class="form-group">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")), restaurants_path, :class => 'btn btn-default' %>
    </div>




<% end %>


  </div>
</div>

app/views/restaurants/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%- model_class = Restaurant -%>
    <div class="page-header">
      <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
    </div>
    <%= render :partial => 'form' %>

  </div>
</div>

app/views/restaurants/index.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <!--<h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>-->
  <div class ="jumbotron">
    <h2>Yelpdemo is the best way to find reviews on local restaurants.</h2>
    <h3>Explore the favorite diners, pastry shops, and eateries in your community.<br />
        Leave reviews and ratings for your fellow foodies.</h3>
  </div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:website) %></th>
      <% if user_signed_in? && current_user.admin? %>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant_path(restaurant) %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone %></td>
        <td><%= link_to restaurant.website, restaurant.website %></td>
        <% if user_signed_in? && current_user.admin? %>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      restaurant_path(restaurant), :class => 'btn btn-primary btn-xs' %>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_restaurant_path(restaurant), :class => 'btn btn-default btn-xs' %>

          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      restaurant_path(restaurant),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if user_signed_in? && current_user.admin? %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
            new_restaurant_path,
            :class => 'btn btn-primary' %>
<% end %>

app/views/restaurants/new.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/restaurants/search.html.erb
<table class="table table-hover table-condensed">
  <thead>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Website</th>
    <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
    <% end %>
  </tr>
  </thead>

  <tbody>
  <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone %></td>
        <td><%= link_to restaurant.website, restaurant.website %></td>
        <% if user_signed_in? && current_user.admin? %>
            <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-link" %></td>
            <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/restaurants/show.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%= @restaurant.name %> - <%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="row">

    <div class="col-md-3">

      <%= image_tag @restaurant.image_url%>
      <br /><br />
      <div class="star-rating" data-score="<%=@avg_rating %>"></div>
      <p><%= "#{@reviews.length} reviews"%></p>
      <p><strong><%= model_class.human_attribute_name(:address) %>:</strong>
      <%= @restaurant.address %></p>
      <p><strong><%= model_class.human_attribute_name(:phone) %>:</strong>
      <%= @restaurant.phone %></p>
      <p><strong><%= model_class.human_attribute_name(:website) %>:</strong>
      <%= link_to @restaurant.website,@restaurant.website %></p>

      <% if user_signed_in? %>
        <%= link_to "Write a  Review", new_restaurant_review_path(@restaurant), :class => 'btn btn-primary'  %>
      <% end %>

      <br /><br />

      <iframe
      width="230"
      height="230"
      frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDYwTOCK8GFuDQvWeJiiSoraMSY5Ob6__4&q=<%= @restaurant.address.parameterize %>&zoom=14">
      </iframe>

      <% if user_signed_in? && current_user.admin? %>
          <div class="">
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_restaurant_path(@restaurant) %> |

            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        restaurant_path(@restaurant),
                        :method => 'delete',
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }
            %>
          </div>
      <% end %>


    </div>
    <div class="col-md-9">

        <div>
          <% if @reviews.blank? %>
              <h3>No reviews yet. Be the first to write one!</h3>
          <% else %>
              <table class="table">
                <tbody>
                    <% @reviews.each do |review| %>
                    <tr>
                      <td class="col-md-3">
                        <h4><%= "#{review.user.first_name.capitalize} #{review.user.last_name[0].capitalize}." %></h4>
                        <p><%= review.created_at.strftime("%-d %b %Y")%></p>
                      </td>
                      <td class="col-md-9">
                        <div class="star-rating" data-score="<%= review.rating %>"></div>
                        <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>
                        <% if user_signed_in? %>
                            <% if (review.user == current_user) || (current_user.admin?) %>
                                <p>
                                <%= link_to "Edit", edit_restaurant_review_path(@restaurant, review) %> |
                                <%= link_to "Delete", restaurant_review_path(@restaurant, review), method: :delete,
                                    :data => {:confirm => t('.confirm', :default => t("helpers.link.confirm", :default => 'Are you sure?') )}
                                %>
                                </p>
                            <% end %>
                        <% end %>

                      </td>
                    </tr>
                    <% end %>
                </tbody>
              </table>
          <% end %>

        </div>
    </div>
    <div class="clearfix"></div>
</div>