config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  
  resources :restaurants do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end

  get 'pages/about'

  get 'pages/contact'

  root 'restaurants#index'

end

app/views/layouts/_footer.html.erb
<footer>
  <%= image_tag "/assets/images/happy_footer.png" %>
  <div class="container-fluid">
    <p class="text-muted">&copy; Company 2015</p>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "yelp!", root_path, class: "navbar-brand" %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "About Us", pages_about_path  %></li>
        <li><%= link_to "Contact", pages_contact_path  %></li>
      </ul>
      <%= form_tag search_restaurants_path, method: :get, class: "navbar-form navbar-left" do %>
            <%= text_field_tag :search, params[:search], class: "form-control" %>
          <button type="submit" class="btn"><span class="fa fa-search"></span></button>
      <% end %>
      <!--<form class="navbar-form  navbar-left">
        <input type="text" class="form-control" placeholder="Search...">
      </form>-->
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Yelpdemo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

  </head>
  <body>

    <%= render partial: 'layouts/nav' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">

          <%= bootstrap_flash %>

          <%= yield %>
        </div>
      </div><!--/row-->



    </div> <!-- /container -->

    <%= render partial: 'layouts/footer' %>

  </body>
</html>

app/views/layouts/two_column.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Yelpdemo" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

</head>
<body>

<%= render partial: 'layouts/nav' %>

<div class="container">
  <div class="row">
    <div class="col-lg-9">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
    <div class="col-lg-3">
      <div class="well sidebar-nav">
        <h3>Sidebar</h3>
        <ul class="nav nav-list">
          <li class="nav-header">Sidebar</li>
          <li><%= link_to "Link1", "/path1"  %></li>
          <li><%= link_to "Link2", "/path2"  %></li>
          <li><%= link_to "Link3", "/path3"  %></li>
        </ul>
      </div><!--/.well -->
    </div><!--/span-->
  </div><!--/row-->

</div> <!-- /container -->

<%= render partial: 'layouts/footer' %>

</body>
</html>